[workspace]
resolver = "2"
members = [
    "packages/threegis-core-wasm"
]

[patch.crates-io]
# csgrs = { path = "vendor/csgrs" }
# geo-buf = { path = "vendor/geo-buf" }
# home = { path = "vendor/home" }

[profile.release]
opt-level = 3
lto = true
